[workspace]
resolver = "3"
members = ["crates/rules"]

[workspace.dependencies]
thiserror = { version = "2.0.21" }
criterion = { version = "0.8.2" }

[workspace.lints.rust]
unsafe_code = "forbid"
unreachable_pub = "warn"

[workspace.lints.clippy]
disallowed_types = "deny"
disallowed_methods = "deny"
